language: php

#env:
#    global:
#        - SYMFONY_DEPRECATIONS_HELPER: weak

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

sudo: false

before_install:
  - composer self-update

install: composer update $COMPOSER_FLAGS --prefer-dist

#script: if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then phpunit --coverage-clover=coverage.clover; else phpunit; fi
#after_script:
#  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi

